version: 0.2
phases:
     install:
       runtime-versions:
         nodejs: 20
       commands:
         - npm install -g appium webdriverio
         - npm install
     build:
       commands:
         - npm run test
